// PSI-90 Guardrail Data — sourced directly from AlignIQ deck
const PSI_DATA = [
  {
    id: 'PSI-03',
    title: 'Pressure Ulcer Rate',
    penalty: 'HAC Reduction Program — hospital-acquired pressure injury penalty',
    icd: 'L89.xx3 / L89.xx4 / L89.xx0 / L89.xx6',
    risk: 'high',
    hears: [
      '"Pressure ulcer" / "pressure injury"',
      '"Stage 3" or "Stage 4" near wound',
      '"Unstageable" / "deep tissue injury"',
      '"Skin breakdown" at sacrum, coccyx, heel, hip',
    ],
    cdi_instinct: [
      'Was this in the ADMISSION skin assessment? Any stage present on arrival = POA',
      'Is this a nursing home transfer? Wounds often arrive undocumented',
      'Who staged this? Physician language is NOT sufficient — wound care RN assessment required',
      'Could this be a deep tissue injury that was invisible on admission?',
    ],
    confirm: [
      'Formal wound care nursing assessment confirms Stage 3, 4, unstageable, or DTI',
      'Admission skin assessment reviewed — wound NOT present at Stage 3+ on arrival',
      'Transfer history reviewed — no prior facility wound attribution',
      'Stage escalation documented AFTER admission date',
    ],
    never: 'Stage 3+ code on physician wound description alone — wound care RN assessment required',
  },
  {
    id: 'PSI-06',
    title: 'Iatrogenic Pneumothorax Rate',
    penalty: 'HAC Reduction Program — accidental lung puncture during procedure',
    icd: 'J95.811 / J93.0 / J93.81 / J93.83',
    risk: 'high',
    hears: [
      '"Chest tube placed" / "pleural drainage"',
      '"Pneumothorax" / "collapsed lung"',
      '"Pleural space entered" / "lung decompressed"',
      '"Thoracentesis" / "pleural effusion drained"',
    ],
    cdi_instinct: [
      'Was this PLANNED (therapeutic drainage) or did something go WRONG?',
      'Did this happen during a procedure with known pleural proximity (central line, thoracentesis)?',
      'Was the pneumothorax pre-existing — present on admission imaging?',
      'Did the physician document the pneumothorax as procedural complication vs. spontaneous?',
    ],
    confirm: [
      'Pneumothorax was NOT present on admission imaging',
      'Pneumothorax occurred during or directly attributable to a procedure',
      'Physician explicitly documents iatrogenic causation',
      'Chest tube or intervention was for the iatrogenic event — not therapeutic for other reasons',
    ],
    never: 'Pneumothorax code in a patient with chest tube placement when admission imaging showed pre-existing pneumothorax — must be confirmed as procedure-caused',
  },
  {
    id: 'PSI-08',
    title: 'In-Hospital Fall with Fracture Rate',
    penalty: 'HAC Reduction Program — new fracture resulting from inpatient fall',
    icd: 'W19.XXXA + S72.xx / S82.xx / S52.xx / S42.xx',
    risk: 'high',
    hears: [
      '"Patient fell" / "found on floor" / "fall from bed"',
      '"Hip fracture" near fall language',
      '"Fracture noted" / "X-ray after fall"',
      '⚠ Fall code + fracture code = AUTOMATIC PSI-08 trigger',
    ],
    cdi_instinct: [
      'Was the fracture the REASON they were admitted — or did it happen DURING the stay?',
      'Was there admission imaging showing no prior fracture?',
      'Did the fall CAUSE the fracture — or did a fracture CAUSE the fall?',
      'Metastatic cancer or severe osteoporosis can cause spontaneous fractures before a fall',
    ],
    confirm: [
      'Post-fall imaging confirms a NEW fracture — not present on admission',
      'Fall event occurred DURING this inpatient admission',
      'Fracture first documented AFTER fall timestamp',
      'Physician documents fall → fracture causation (not fracture → fall)',
    ],
    never: 'Fall code + fracture code together without imaging confirmation of NEW fracture — pathological fractures can pre-exist',
  },
  {
    id: 'PSI-09',
    title: 'Postop Hemorrhage or Hematoma Rate',
    penalty: 'HAC Reduction Program — significant postop bleeding requiring additional treatment',
    icd: 'T81.0XXA / T81.010A / M96.830 / M96.840',
    risk: 'medium',
    hears: [
      '"Hematoma" / "hemorrhage" / "bleeding postop"',
      '"Return to OR for bleeding"',
      '"Evacuation of hematoma" / "transfusion given"',
      '"Drain output increased" / "blood collection"',
    ],
    cdi_instinct: [
      'Is this patient on anticoagulants? Coumadin or Plavix patients bleed more — expected, not always a complication',
      'Was this CLINICALLY SIGNIFICANT or just an incidental CT finding nobody treated?',
      'Was the transfusion for THIS bleeding or for pre-existing anemia?',
      'Did the physician explicitly call this a COMPLICATION requiring treatment?',
    ],
    confirm: [
      'Bleeding required ADDITIONAL INTERVENTION — return to OR, transfusion for hemorrhage, or procedural drainage',
      'Physician explicitly documents as complication requiring treatment',
      'Anticoagulation or coagulopathy is NOT the primary explanation',
      'Bleeding occurred AFTER the procedure — not present pre-surgery',
    ],
    never: 'Hemorrhage/hematoma complication code for incidental findings — minor postop bleeding is expected and does NOT trigger PSI-09',
  },
  {
    id: 'PSI-10',
    title: 'Postop AKI Requiring Dialysis',
    penalty: 'HAC Reduction Program — new dialysis initiation after elective surgery',
    icd: 'N17.0–N17.9 + 5A1D00Z / 5A1D60Z / 5A1D70Z',
    risk: 'high',
    hears: [
      '"Dialysis" / "CRRT" / "hemodialysis"',
      '"Renal failure postop" / "AKI"',
      '"Nephrology consulted" / "creatinine rising"',
      '"Kidney not recovering" / "renal replacement"',
    ],
    cdi_instinct: [
      'Was this patient ALREADY on dialysis before admission? Most common false-positive for PSI-10',
      'Was dialysis ACTUALLY started or just nephrology consulted?',
      'What is their BASELINE creatinine — is this really a change from normal?',
      'Did the physician explicitly document NEW AKI requiring dialysis initiation?',
    ],
    confirm: [
      'Patient was NOT dialysis-dependent or have ESRD prior to this admission',
      'Dialysis was ACTUALLY PERFORMED — not just ordered or consulted',
      'Dialysis indication = NEW AKI — not ongoing ESRD management',
      'AKI developed AFTER the surgical procedure — not present on admission',
    ],
    never: 'AKI requiring dialysis code based on nephrology consult or rising creatinine alone — dialysis must be confirmed as new initiation for new AKI',
  },
  {
    id: 'PSI-11',
    title: 'Postop Respiratory Failure Rate',
    penalty: 'HAC Reduction Program — unexpected respiratory failure after elective surgery',
    icd: 'J95.1 / J95.2 / J96.00 / J96.01 / J96.02',
    risk: 'high',
    hears: [
      '"Still on the vent" / "failed extubation"',
      '"Reintubated" / "couldn\'t wean"',
      '"Back on the vent" / "prolonged ventilation"',
      '"Respiratory failure" / "hypoxic"',
    ],
    cdi_instinct: [
      'What procedure did they have? Cardiac, thoracic, major abdominal — staying on the vent is PLANNED',
      'Did the patient have lung disease before surgery? COPD, fibrosis, obesity hypoventilation = expected difficulty weaning',
      'Did the physician say this was an UNEXPECTED complication — or just vent management?',
      'Slow weaning is NOT respiratory failure — physician must explicitly document it as a complication',
    ],
    confirm: [
      'Postop ventilation was NOT expected or planned for this procedure type',
      'Patient had NO pre-existing pulmonary conditions explaining vent dependency',
      'Physician EXPLICITLY documents respiratory failure as UNEXPECTED complication',
      'Reintubation — if it occurred — was UNPLANNED',
    ],
    never: 'Respiratory failure code based on ventilator language alone — planned postop vent management is NOT a complication',
  },
  {
    id: 'PSI-12',
    title: 'Perioperative PE or DVT Rate',
    penalty: 'HAC Reduction Program — blood clot coded as hospital-acquired on surgical patient',
    icd: 'I26.01 / I26.09 / I26.99 / I82.401 / I82.411 / I82.4xx',
    risk: 'medium',
    hears: [
      '"DVT" / "deep vein thrombosis" / "blood clot"',
      '"Pulmonary embolism" / "PE confirmed"',
      '"Lovenox ordered" / "anticoagulation initiated"',
      '"Positive duplex" / "CTA positive"',
    ],
    cdi_instinct: [
      'Is this an ONCOLOGY patient? Cancer patients clot — this may be disease-related, not procedure-related',
      'Was there imaging BEFORE surgery? Without a pre-admission duplex — how do we know the clot wasn\'t already there?',
      'Is Lovenox for PREVENTION or TREATMENT? Lovenox on every surgical patient ≠ DVT diagnosis',
      'Did the physician actually say DVT as a confirmed diagnosis — or are they treating empirically?',
    ],
    confirm: [
      'Imaging (duplex, CTA, V/Q) confirms a clot EXISTS — not just suspected',
      'Physician documents DVT or PE as a CONFIRMED diagnosis',
      'Anticoagulation is THERAPEUTIC dose — not prophylactic',
      'If oncology or clotting disorder present — physician documents procedure-related causation',
    ],
    never: 'DVT/PE code based on anticoagulation orders alone — Lovenox prophylaxis is NOT a DVT diagnosis and must never trigger a code suggestion',
  },
  {
    id: 'PSI-13',
    title: 'Postop Sepsis Rate',
    penalty: 'HAC Reduction Program — one of the highest-scrutiny and highest-penalty PSI events',
    icd: 'A40.0–A40.9 / A41.01–A41.9 / R65.20 / R65.21',
    risk: 'high',
    hears: [
      '"Sepsis" / "septic" / "septic shock"',
      '"Broad spectrum antibiotics" / "Vancomycin / Pip-tazo"',
      '"Fever postop" / "source control" / "bacteremia"',
      '"SIRS" / "white count elevated"',
    ],
    cdi_instinct: [
      'Did the physician actually SAY SEPSIS? Antibiotics for fever ≠ sepsis — physicians treat empirically constantly',
      'Does this meet Sepsis-3? Need BOTH suspected infection source AND organ dysfunction — elevated WBC alone is not enough',
      'When did fever start? Day 1 postop fever is almost always expected inflammation',
      'Was infection already present BEFORE surgery? Pre-existing UTI or pneumonia = POA, not hospital-acquired',
    ],
    confirm: [
      'Physician EXPLICITLY documents \'sepsis\' as a diagnosis — not just infection, fever, or antibiotics',
      'Documentation supports Sepsis-3: infection source AND organ dysfunction evidence',
      'Infection or sepsis was NOT present on admission',
      'Antibiotics are for TREATMENT — not surgical prophylaxis',
    ],
    never: 'Sepsis code based on antibiotics or postop fever alone — Vancomycin and Pip-tazo do NOT confirm sepsis and must never trigger a sepsis code suggestion',
  },
  {
    id: 'PSI-14',
    title: 'Postop Wound Dehiscence Rate',
    penalty: 'HAC Reduction Program — fascial wound disruption after abdominopelvic surgery',
    icd: 'T81.30XA / T81.31XA / T81.32XA',
    risk: 'medium',
    hears: [
      '"Dehiscence" / "fascial dehiscence" / "evisceration"',
      '"Wound separation" / "wound opened"',
      '"Wound VAC applied" / "wound not healing"',
      '"Return to OR for wound" / "wound breakdown"',
    ],
    cdi_instinct: [
      'What LAYER is involved? Superficial skin separation in obese or diabetic patients is common — does NOT trigger PSI-14',
      'Did this require a RETURN TO OR for repair? Wound VAC alone = wound management, not dehiscence',
      'What is this patient\'s risk profile? Obesity, diabetes, steroids, malnutrition — expected wound healing challenges',
      'Did the SURGEON document what layer was disrupted — not just nursing wound appearance?',
    ],
    confirm: [
      'Surgeon explicitly documents FASCIAL layer or internal operative wound disruption',
      'Required OPERATIVE REPAIR — return to OR for wound closure',
      'Procedure was an ABDOMINOPELVIC OR procedure (PSI-14 denominator requirement)',
      'Wound disruption occurred AFTER surgery — not present pre-operatively',
    ],
    never: 'Wound dehiscence code for superficial skin separation — fascial layer disruption must be explicitly documented by the surgeon',
  },
  {
    id: 'PSI-15',
    title: 'Abdominopelvic Accidental Puncture or Laceration',
    penalty: 'HAC Reduction Program — HIGHEST false-positive risk in the PSI-90 composite',
    icd: 'T81.520A / T81.521A / T81.522A / K91.71',
    risk: 'very-high',
    hears: [
      '"Entered the bowel" / "bladder injury" / "bowel entry"',
      '"Inadvertent cystotomy" / "vessel injury"',
      '"Repaired incidentally" / "unintended entry"',
      '"Enterotomy" / "dissection near [organ]"',
    ],
    cdi_instinct: [
      'Was this truly ACCIDENTAL or just how surgeons describe complex dissection near adhesions?',
      'Did the surgeon use the words: accidental, inadvertent, or unintended? Those SPECIFIC words matter',
      'What is this patient\'s surgical history? Prior abdominal surgeries + radiation = expected proximity to organs',
      'Did this require ADDITIONAL repair beyond what was planned — or was it part of the dissection?',
    ],
    confirm: [
      'Surgeon EXPLICITLY uses: accidental, inadvertent, unintended, or unexpected',
      'Injured structure was NOT expected in operative field given procedure and patient history',
      'Injury required ADDITIONAL repair beyond planned procedure scope',
      'Physician characterizes this as a complication in the operative note',
    ],
    never: 'Accidental puncture code based on anatomical proximity language — ambiguous language = FALSE. Surgeon must explicitly say accidental. Supervisor review required before any release.',
  },
];

// LIVE DEMO SCENARIOS — three high-stakes false-positive cases
const SCENARIOS = [
  {
    psi: 'PSI-13',
    name: 'The Postop Fever',
    setting: 'POD 1 after colectomy. Nurse pages overnight team.',
    provider_quote: 'Patient febrile to 38.7 postop, white count up to 14, started broad-spectrum Vancomycin and Pip-tazo. Will continue to monitor for sepsis.',
    ai_detection: 'A41.9 — Sepsis, unspecified',
    ai_confidence: '0.84',
    conditions: [
      { text: 'Physician explicitly documents \'sepsis\' as a confirmed diagnosis', met: false, evidence: 'Provider said "monitor for sepsis" — that is empiric treatment, not a sepsis diagnosis.' },
      { text: 'Documentation supports Sepsis-3 (infection source + organ dysfunction)', met: false, evidence: 'Only WBC elevation noted. No documented infection source, no organ dysfunction.' },
      { text: 'Infection or sepsis was NOT present on admission', met: 'unknown', evidence: 'Admission status not yet reviewed — but POD 1 fever is typically inflammatory, not septic.' },
      { text: 'Antibiotics are for TREATMENT — not prophylaxis or empiric coverage', met: false, evidence: 'Antibiotics started for fever with unclear source — empiric, not confirmed treatment for sepsis.' },
    ],
    outcome: 'HOLD',
    outcome_reason: 'A sepsis code applied here would inflate PSI-13 — a postop sepsis miscoding can drive HAC penalty exposure for the institution. The provider is treating a fever; the AI is reading "sepsis" into empiric antibiotic language.',
    cdi_query: 'Please clarify if patient meets Sepsis-3 criteria, or if antibiotics are empiric for unspecified postop fever. Document infection source and organ dysfunction if sepsis is suspected.',
    business_impact: 'A single false-positive PSI-13 code can push a borderline hospital into the bottom HAC quartile — a 1% Medicare base operating DRG reduction worth ~$500K–$5M+ annually.',
  },
  {
    psi: 'PSI-15',
    name: 'The Adhesion Dissection',
    setting: 'OR. Surgeon dictating operative note during complex hysterectomy.',
    provider_quote: 'Extensive adhesions from prior C-sections. During dissection near the bladder, we entered a small portion of the bladder wall. This was repaired primarily with 3-0 vicryl in two layers. Procedure completed without further incident.',
    ai_detection: 'T81.520A — Unspecified accidental puncture or laceration during procedure',
    ai_confidence: '0.78',
    conditions: [
      { text: 'Surgeon EXPLICITLY uses: accidental, inadvertent, unintended, or unexpected', met: false, evidence: 'None of those words appear. Surgeon describes "during dissection" — descriptive, not characterized as accidental.' },
      { text: 'Injured structure was NOT expected in operative field', met: false, evidence: 'Bladder is anatomically expected in this surgical field; prior C-sections create known adhesion risk in this area.' },
      { text: 'Injury required ADDITIONAL repair beyond planned procedure scope', met: 'unknown', evidence: 'Bladder repair was performed — but was this within the expected scope given known adhesions? Unclear.' },
      { text: 'Physician characterizes this as a complication in the operative note', met: false, evidence: 'No language of "complication." Reads as expected operative finding.' },
    ],
    outcome: 'HOLD',
    outcome_reason: 'This is the highest-stakes false-positive scenario in PSI-90. Coding bladder entry during complex dissection as "accidental" when the surgeon did not use that language inflates PSI-15 — the measure with the highest false-positive risk in the composite.',
    cdi_query: 'Please clarify in the operative note whether the bladder entry was accidental, inadvertent, or unintended — or whether it was an expected finding given the adhesion burden. Specific language affects coding.',
    business_impact: 'PSI-15 is weighted heavily in the PSI-90 composite. A single false-positive can affect HAC quartile placement and Star Rating Safety of Care quartile — driving the new 2026 4-star cap.',
  },
  {
    psi: 'PSI-03',
    name: 'The Hidden Pressure Ulcer',
    setting: 'Hospital day 3. Nurse notes wound during routine repositioning.',
    provider_quote: 'Noted Stage 3 pressure ulcer to sacrum during turn. Wound care consulted. Patient admitted from skilled nursing facility three days ago.',
    ai_detection: 'L89.153 — Pressure ulcer of sacral region, stage 3',
    ai_confidence: '0.91',
    conditions: [
      { text: 'Formal wound care nursing assessment confirms Stage 3, 4, unstageable, or DTI', met: 'unknown', evidence: 'Wound care consulted but assessment not yet documented. Floor nurse staged — insufficient for code.' },
      { text: 'Admission skin assessment reviewed — wound NOT present at Stage 3+ on arrival', met: 'unknown', evidence: 'Admission assessment must be retrieved. Patient came from SNF — high probability wound was POA.' },
      { text: 'Transfer history reviewed — no prior facility wound attribution', met: false, evidence: 'Patient admitted from SNF 3 days ago. SNF transfer documentation must be reviewed before POA determination.' },
      { text: 'Stage escalation documented AFTER admission date', met: 'unknown', evidence: 'No prior staging on record yet — but absence of documentation does NOT prove absence of POA wound.' },
    ],
    outcome: 'HOLD',
    outcome_reason: 'SNF transfer + day 3 wound discovery is the textbook POA risk pattern. Coding this as hospital-acquired without admission skin assessment and SNF records is the single most common driver of false PSI-03 attribution.',
    cdi_query: 'Please review the admission skin assessment and SNF transfer documentation. Confirm whether this Stage 3 pressure injury was present on admission (POA = Y) or hospital-acquired (POA = N).',
    business_impact: 'Hospital-acquired pressure injuries trigger the HAC Reduction Program. A single mis-attributed Stage 3+ pressure ulcer from a SNF transfer can be the determining event for a hospital landing in the bottom HAC quartile.',
  },
];
