// PSI-90 Guardrail Data — sourced directly from AlignIQ deck
const PSI_DATA = [
  {
    id: 'PSI-03',
    title: 'Pressure Ulcer Rate',
    penalty: 'HAC Reduction Program — hospital-acquired pressure injury penalty',
    icd: 'L89.xx3 / L89.xx4 / L89.xx0 / L89.xx6',
    risk: 'high',
    hears: [
      '"Pressure ulcer" / "pressure injury"',
      '"Stage 3" or "Stage 4" near wound',
      '"Unstageable" / "deep tissue injury"',
      '"Skin breakdown" at sacrum, coccyx, heel, hip',
    ],
    cdi_instinct: [
      'Was this in the ADMISSION skin assessment? Any stage present on arrival = POA',
      'Is this a nursing home transfer? Wounds often arrive undocumented',
      'Who staged this? Physician language is NOT sufficient — wound care RN assessment required',
      'Could this be a deep tissue injury that was invisible on admission?',
    ],
    confirm: [
      'Formal wound care nursing assessment confirms Stage 3, 4, unstageable, or DTI',
      'Admission skin assessment reviewed — wound NOT present at Stage 3+ on arrival',
      'Transfer history reviewed — no prior facility wound attribution',
      'Stage escalation documented AFTER admission date',
    ],
    never: 'Stage 3+ code on physician wound description alone — wound care RN assessment required',
  },
  {
    id: 'PSI-06',
    title: 'Iatrogenic Pneumothorax Rate',
    penalty: 'HAC Reduction Program — accidental lung puncture during procedure',
    icd: 'J95.811 / J93.0 / J93.81 / J93.83',
    risk: 'high',
    hears: [
      '"Chest tube placed" / "pleural drainage"',
      '"Pneumothorax" / "collapsed lung"',
      '"Pleural space entered" / "lung decompressed"',
      '"Thoracentesis" / "pleural effusion drained"',
    ],
    cdi_instinct: [
      'Was this PLANNED (therapeutic drainage) or did something go WRONG?',
      'Did this happen during a procedure with known pleural proximity (central line, thoracentesis)?',
      'Was the pneumothorax pre-existing — present on admission imaging?',
      'Did the physician document the pneumothorax as procedural complication vs. spontaneous?',
    ],
    confirm: [
      'Pneumothorax was NOT present on admission imaging',
      'Pneumothorax occurred during or directly attributable to a procedure',
      'Physician explicitly documents iatrogenic causation',
      'Chest tube or intervention was for the iatrogenic event — not therapeutic for other reasons',
    ],
    never: 'Pneumothorax code in a patient with chest tube placement when admission imaging showed pre-existing pneumothorax — must be confirmed as procedure-caused',
  },
  {
    id: 'PSI-08',
    title: 'In-Hospital Fall with Fracture Rate',
    penalty: 'HAC Reduction Program — new fracture resulting from inpatient fall',
    icd: 'W19.XXXA + S72.xx / S82.xx / S52.xx / S42.xx',
    risk: 'high',
    hears: [
      '"Patient fell" / "found on floor" / "fall from bed"',
      '"Hip fracture" near fall language',
      '"Fracture noted" / "X-ray after fall"',
      '⚠ Fall code + fracture code = AUTOMATIC PSI-08 trigger',
    ],
    cdi_instinct: [
      'Was the fracture the REASON they were admitted — or did it happen DURING the stay?',
      'Was there admission imaging showing no prior fracture?',
      'Did the fall CAUSE the fracture — or did a fracture CAUSE the fall?',
      'Metastatic cancer or severe osteoporosis can cause spontaneous fractures before a fall',
    ],
    confirm: [
      'Post-fall imaging confirms a NEW fracture — not present on admission',
      'Fall event occurred DURING this inpatient admission',
      'Fracture first documented AFTER fall timestamp',
      'Physician documents fall → fracture causation (not fracture → fall)',
    ],
    never: 'Fall code + fracture code together without imaging confirmation of NEW fracture — pathological fractures can pre-exist',
  },
  {
    id: 'PSI-09',
    title: 'Postop Hemorrhage or Hematoma Rate',
    penalty: 'HAC Reduction Program — significant postop bleeding requiring additional treatment',
    icd: 'T81.0XXA / T81.010A / M96.830 / M96.840',
    risk: 'medium',
    hears: [
      '"Hematoma" / "hemorrhage" / "bleeding postop"',
      '"Return to OR for bleeding"',
      '"Evacuation of hematoma" / "transfusion given"',
      '"Drain output increased" / "blood collection"',
    ],
    cdi_instinct: [
      'Is this patient on anticoagulants? Coumadin or Plavix patients bleed more — expected, not always a complication',
      'Was this CLINICALLY SIGNIFICANT or just an incidental CT finding nobody treated?',
      'Was the transfusion for THIS bleeding or for pre-existing anemia?',
      'Did the physician explicitly call this a COMPLICATION requiring treatment?',
    ],
    confirm: [
      'Bleeding required ADDITIONAL INTERVENTION — return to OR, transfusion for hemorrhage, or procedural drainage',
      'Physician explicitly documents as complication requiring treatment',
      'Anticoagulation or coagulopathy is NOT the primary explanation',
      'Bleeding occurred AFTER the procedure — not present pre-surgery',
    ],
    never: 'Hemorrhage/hematoma complication code for incidental findings — minor postop bleeding is expected and does NOT trigger PSI-09',
  },
  {
    id: 'PSI-10',
    title: 'Postop AKI Requiring Dialysis',
    penalty: 'HAC Reduction Program — new dialysis initiation after elective surgery',
    icd: 'N17.0–N17.9 + 5A1D00Z / 5A1D60Z / 5A1D70Z',
    risk: 'high',
    hears: [
      '"Dialysis" / "CRRT" / "hemodialysis"',
      '"Renal failure postop" / "AKI"',
      '"Nephrology consulted" / "creatinine rising"',
      '"Kidney not recovering" / "renal replacement"',
    ],
    cdi_instinct: [
      'Was this patient ALREADY on dialysis before admission? Most common false-positive for PSI-10',
      'Was dialysis ACTUALLY started or just nephrology consulted?',
      'What is their BASELINE creatinine — is this really a change from normal?',
      'Did the physician explicitly document NEW AKI requiring dialysis initiation?',
    ],
    confirm: [
      'Patient was NOT dialysis-dependent or have ESRD prior to this admission',
      'Dialysis was ACTUALLY PERFORMED — not just ordered or consulted',
      'Dialysis indication = NEW AKI — not ongoing ESRD management',
      'AKI developed AFTER the surgical procedure — not present on admission',
    ],
    never: 'AKI requiring dialysis code based on nephrology consult or rising creatinine alone — dialysis must be confirmed as new initiation for new AKI',
  },
  {
    id: 'PSI-11',
    title: 'Postop Respiratory Failure Rate',
    penalty: 'HAC Reduction Program — unexpected respiratory failure after elective surgery',
    icd: 'J95.1 / J95.2 / J96.00 / J96.01 / J96.02',
    risk: 'high',
    hears: [
      '"Still on the vent" / "failed extubation"',
      '"Reintubated" / "couldn\'t wean"',
      '"Back on the vent" / "prolonged ventilation"',
      '"Respiratory failure" / "hypoxic"',
    ],
    cdi_instinct: [
      'What procedure did they have? Cardiac, thoracic, major abdominal — staying on the vent is PLANNED',
      'Did the patient have lung disease before surgery? COPD, fibrosis, obesity hypoventilation = expected difficulty weaning',
      'Did the physician say this was an UNEXPECTED complication — or just vent management?',
      'Slow weaning is NOT respiratory failure — physician must explicitly document it as a complication',
    ],
    confirm: [
      'Postop ventilation was NOT expected or planned for this procedure type',
      'Patient had NO pre-existing pulmonary conditions explaining vent dependency',
      'Physician EXPLICITLY documents respiratory failure as UNEXPECTED complication',
      'Reintubation — if it occurred — was UNPLANNED',
    ],
    never: 'Respiratory failure code based on ventilator language alone — planned postop vent management is NOT a complication',
  },
  {
    id: 'PSI-12',
    title: 'Perioperative PE or DVT Rate',
    penalty: 'HAC Reduction Program — blood clot coded as hospital-acquired on surgical patient',
    icd: 'I26.01 / I26.09 / I26.99 / I82.401 / I82.411 / I82.4xx',
    risk: 'medium',
    hears: [
      '"DVT" / "deep vein thrombosis" / "blood clot"',
      '"Pulmonary embolism" / "PE confirmed"',
      '"Lovenox ordered" / "anticoagulation initiated"',
      '"Positive duplex" / "CTA positive"',
    ],
    cdi_instinct: [
      'Is this an ONCOLOGY patient? Cancer patients clot — this may be disease-related, not procedure-related',
      'Was there imaging BEFORE surgery? Without a pre-admission duplex — how do we know the clot wasn\'t already there?',
      'Is Lovenox for PREVENTION or TREATMENT? Lovenox on every surgical patient ≠ DVT diagnosis',
      'Did the physician actually say DVT as a confirmed diagnosis — or are they treating empirically?',
    ],
    confirm: [
      'Imaging (duplex, CTA, V/Q) confirms a clot EXISTS — not just suspected',
      'Physician documents DVT or PE as a CONFIRMED diagnosis',
      'Anticoagulation is THERAPEUTIC dose — not prophylactic',
      'If oncology or clotting disorder present — physician documents procedure-related causation',
    ],
    never: 'DVT/PE code based on anticoagulation orders alone — Lovenox prophylaxis is NOT a DVT diagnosis and must never trigger a code suggestion',
  },
  {
    id: 'PSI-13',
    title: 'Postop Sepsis Rate',
    penalty: 'HAC Reduction Program — one of the highest-scrutiny and highest-penalty PSI events',
    icd: 'A40.0–A40.9 / A41.01–A41.9 / R65.20 / R65.21',
    risk: 'high',
    hears: [
      '"Sepsis" / "septic" / "septic shock"',
      '"Broad spectrum antibiotics" / "Vancomycin / Pip-tazo"',
      '"Fever postop" / "source control" / "bacteremia"',
      '"SIRS" / "white count elevated"',
    ],
    cdi_instinct: [
      'Did the physician actually SAY SEPSIS? Antibiotics for fever ≠ sepsis — physicians treat empirically constantly',
      'Does this meet Sepsis-3? Need BOTH suspected infection source AND organ dysfunction — elevated WBC alone is not enough',
      'When did fever start? Day 1 postop fever is almost always expected inflammation',
      'Was infection already present BEFORE surgery? Pre-existing UTI or pneumonia = POA, not hospital-acquired',
    ],
    confirm: [
      'Physician EXPLICITLY documents \'sepsis\' as a diagnosis — not just infection, fever, or antibiotics',
      'Documentation supports Sepsis-3: infection source AND organ dysfunction evidence',
      'Infection or sepsis was NOT present on admission',
      'Antibiotics are for TREATMENT — not surgical prophylaxis',
    ],
    never: 'Sepsis code based on antibiotics or postop fever alone — Vancomycin and Pip-tazo do NOT confirm sepsis and must never trigger a sepsis code suggestion',
  },
  {
    id: 'PSI-14',
    title: 'Postop Wound Dehiscence Rate',
    penalty: 'HAC Reduction Program — fascial wound disruption after abdominopelvic surgery',
    icd: 'T81.30XA / T81.31XA / T81.32XA',
    risk: 'medium',
    hears: [
      '"Dehiscence" / "fascial dehiscence" / "evisceration"',
      '"Wound separation" / "wound opened"',
      '"Wound VAC applied" / "wound not healing"',
      '"Return to OR for wound" / "wound breakdown"',
    ],
    cdi_instinct: [
      'What LAYER is involved? Superficial skin separation in obese or diabetic patients is common — does NOT trigger PSI-14',
      'Did this require a RETURN TO OR for repair? Wound VAC alone = wound management, not dehiscence',
      'What is this patient\'s risk profile? Obesity, diabetes, steroids, malnutrition — expected wound healing challenges',
      'Did the SURGEON document what layer was disrupted — not just nursing wound appearance?',
    ],
    confirm: [
      'Surgeon explicitly documents FASCIAL layer or internal operative wound disruption',
      'Required OPERATIVE REPAIR — return to OR for wound closure',
      'Procedure was an ABDOMINOPELVIC OR procedure (PSI-14 denominator requirement)',
      'Wound disruption occurred AFTER surgery — not present pre-operatively',
    ],
    never: 'Wound dehiscence code for superficial skin separation — fascial layer disruption must be explicitly documented by the surgeon',
  },
  {
    id: 'PSI-15',
    title: 'Abdominopelvic Accidental Puncture or Laceration',
    penalty: 'HAC Reduction Program — HIGHEST false-positive risk in the PSI-90 composite',
    icd: 'T81.520A / T81.521A / T81.522A / K91.71',
    risk: 'very-high',
    hears: [
      '"Entered the bowel" / "bladder injury" / "bowel entry"',
      '"Inadvertent cystotomy" / "vessel injury"',
      '"Repaired incidentally" / "unintended entry"',
      '"Enterotomy" / "dissection near [organ]"',
    ],
    cdi_instinct: [
      'Was this truly ACCIDENTAL or just how surgeons describe complex dissection near adhesions?',
      'Did the surgeon use the words: accidental, inadvertent, or unintended? Those SPECIFIC words matter',
      'What is this patient\'s surgical history? Prior abdominal surgeries + radiation = expected proximity to organs',
      'Did this require ADDITIONAL repair beyond what was planned — or was it part of the dissection?',
    ],
    confirm: [
      'Surgeon EXPLICITLY uses: accidental, inadvertent, unintended, or unexpected',
      'Injured structure was NOT expected in operative field given procedure and patient history',
      'Injury required ADDITIONAL repair beyond planned procedure scope',
      'Physician characterizes this as a complication in the operative note',
    ],
    never: 'Accidental puncture code based on anatomical proximity language — ambiguous language = FALSE. Surgeon must explicitly say accidental. Supervisor review required before any release.',
  },
];

// LIVE DEMO SCENARIOS — three high-stakes false-positive cases
const SCENARIOS = [
  {
    psi: 'PSI-15',
    name: 'The Enterotomy',
    setting: 'OR. Surgeon dictating operative note after lap-converted-to-open small bowel resection for adhesions.',
    provider_quote: 'During lysis of dense adhesions, enterotomy occurred. Repaired primarily with running 3-0 silk. No further complications.',
    ai_detection: 'T81.520A — Unspecified accidental puncture or laceration during procedure',
    ai_confidence: '0.81',
    conditions: [
      { text: 'Surgeon EXPLICITLY uses: accidental, inadvertent, unintended, or unexpected', met: false, evidence: 'None of those words appear. "Enterotomy occurred" is descriptive — passive voice without characterizing the event as accidental.' },
      { text: 'Injured structure was NOT expected in operative field', met: false, evidence: 'Small bowel is the operative target. Dense adhesions create known proximity and entry risk — this is expected complexity in adhesion lysis.' },
      { text: 'Injury required ADDITIONAL repair beyond planned procedure scope', met: 'unknown', evidence: 'Primary repair was performed — but was this anticipated given the adhesion burden? Unclear whether this exceeded planned scope.' },
      { text: 'Physician characterizes this as a complication in the operative note', met: false, evidence: '"No further complications" suggests the enterotomy was NOT itself characterized as a complication by the surgeon.' },
    ],
    outcome: 'HOLD',
    outcome_reason: 'Enterotomy during adhesiolysis is the highest-volume false-positive trigger for PSI-15. The AI sees "enterotomy" and reaches for the accidental-puncture code — but the surgeon\'s language is descriptive, not characterizing. Without explicit "accidental/inadvertent/unintended," this code cannot release.',
    cdi_query: 'Please clarify in the operative note: was the enterotomy accidental, inadvertent, or unintended — or was it an expected risk of lysis given the adhesion burden? Specific language affects coding and PSI-15 attribution.',
    business_impact: 'PSI-15 is the highest-weighted false-positive risk in the PSI-90 composite. A single inappropriate accidental-puncture code can affect HAC quartile placement and Star Rating Safety of Care quartile — directly driving the new 2026 4-star cap.',
  },
  {
    psi: 'PSI-06',
    name: 'The Cancer Patient Pneumothorax',
    setting: 'Pulmonology procedure suite. Post-thoracentesis for pleural effusion in a patient with metastatic NSCLC.',
    provider_quote: 'Performed thoracentesis for symptomatic pleural effusion, 1.2L removed. Post-procedure CXR shows small apical pneumothorax. Patient has known mets to right lung. Will observe, no chest tube needed.',
    ai_detection: 'J95.811 — Postprocedural pneumothorax',
    ai_confidence: '0.86',
    conditions: [
      { text: 'Pneumothorax was NOT present on admission imaging', met: 'unknown', evidence: 'Pre-procedure imaging needs review. NSCLC patients can have pre-existing pneumothorax from disease progression, prior interventions, or bullous changes.' },
      { text: 'Pneumothorax occurred during or directly attributable to a procedure', met: 'unknown', evidence: 'Temporal relationship to thoracentesis is suggestive — but in metastatic NSCLC patients, spontaneous pneumothorax from tumor erosion is also possible. Causation is not established.' },
      { text: 'Physician explicitly documents iatrogenic causation', met: false, evidence: 'Provider notes "post-procedure pneumothorax" but does NOT use language like "iatrogenic," "procedure-related," or "caused by thoracentesis." Descriptive timing is not attributed causation.' },
      { text: 'Chest tube or intervention was for the iatrogenic event — not therapeutic for other reasons', met: false, evidence: 'Small, observed, NO intervention required. Does not meet PSI-06 clinical significance threshold for a procedural complication.' },
    ],
    outcome: 'HOLD',
    outcome_reason: 'A pneumothorax after thoracentesis in a metastatic NSCLC patient is exactly the scenario PSI-06 was NOT designed to capture. The AI hears temporal sequence and reaches for the iatrogenic code — but the patient\'s underlying disease creates baseline pneumothorax risk that confounds causation.',
    cdi_query: 'Please clarify in the documentation: is this pneumothorax characterized as iatrogenic (procedure-caused), or as a finding in a patient with elevated baseline risk given metastatic lung disease? Specific causation language is required for PSI-06 attribution.',
    business_impact: 'PSI-06 false positives are common in tertiary cancer centers and academic medical institutions — the very hospitals most likely to perform high-volume thoracenteses on patients with metastatic disease. A single mis-attributed iatrogenic pneumothorax inflates PSI-06 risk for the institution.',
  },
  {
    psi: 'PSI-11',
    name: 'The Slow Wean',
    setting: 'CTICU. POD 2 after CABG with prolonged bypass time. Patient has known COPD.',
    provider_quote: 'Patient remains intubated POD 2 with postop respiratory failure. Slow wean given COPD baseline and prolonged pump time. Plan trach if not extubated by POD 5.',
    ai_detection: 'J96.00 — Acute respiratory failure, unspecified',
    ai_confidence: '0.92',
    conditions: [
      { text: 'Postop ventilation was NOT expected or planned for this procedure type', met: false, evidence: 'CABG with prolonged bypass time → continued vent dependency is EXPECTED in the immediate postop period. Not unplanned.' },
      { text: 'Patient had NO pre-existing pulmonary conditions explaining vent dependency', met: false, evidence: 'COPD is explicitly documented as the reason for slow weaning. Pre-existing lung disease is the primary explanation for vent dependency.' },
      { text: 'Physician EXPLICITLY documents respiratory failure as UNEXPECTED complication', met: false, evidence: 'Provider uses the words "respiratory failure" — but characterizes it as "slow wean given COPD baseline and prolonged pump time." This is documentation of expected difficulty, not unexpected complication.' },
      { text: 'Reintubation — if it occurred — was UNPLANNED', met: 'unknown', evidence: 'No reintubation mentioned. Patient has not yet been extubated; this is continued initial vent management, not a failed wean event.' },
    ],
    outcome: 'HOLD',
    outcome_reason: 'This is the most sophisticated false-positive in PSI-90. The provider used the words "respiratory failure" — and a keyword-matching AI will code it. But CDI judgment knows: post-CABG with COPD baseline and prolonged pump time is EXPECTED slow weaning, not unexpected respiratory failure. Provider language is shorthand, not a clinical complication designation.',
    cdi_query: 'Please clarify in the documentation: is the continued vent dependency characterized as an UNEXPECTED postop complication, or as expected slow weaning given pre-existing COPD and prolonged bypass time? "Respiratory failure" terminology may not align with the clinical context as documented.',
    business_impact: 'PSI-11 false positives are especially common in cardiac surgery programs — the very service lines where slow weaning is medically expected. A single inappropriate respiratory-failure code can drive PSI-11 attribution that does not reflect actual unexpected complications.',
  },
];
