// PSI-90 Guardrail Data — sourced directly from AlignIQ deck
const PSI_DATA = [
  {
    id: 'PSI-03',
    title: 'Pressure Ulcer Rate',
    penalty: 'HAC Reduction Program — hospital-acquired pressure injury penalty',
    icd: 'L89.xx3 / L89.xx4 / L89.xx0 / L89.xx6',
    risk: 'high',
    hears: [
      '"Pressure ulcer" / "pressure injury"',
      '"Stage 3" or "Stage 4" near wound',
      '"Unstageable" / "deep tissue injury"',
      '"Skin breakdown" at sacrum, coccyx, heel, hip',
    ],
    cdi_instinct: [
      'Was this in the ADMISSION skin assessment? Any stage present on arrival = POA',
      'Is this a nursing home transfer? Wounds often arrive undocumented',
      'Who staged this? Physician language is NOT sufficient — wound care RN assessment required',
      'Could this be a deep tissue injury that was invisible on admission?',
    ],
    confirm: [
      'Formal wound care nursing assessment confirms Stage 3, 4, unstageable, or DTI',
      'Admission skin assessment reviewed — wound NOT present at Stage 3+ on arrival',
      'Transfer history reviewed — no prior facility wound attribution',
      'Stage escalation documented AFTER admission date',
    ],
    never: 'Stage 3+ code on physician wound description alone — wound care RN assessment required',
  },
  {
    id: 'PSI-06',
    title: 'Iatrogenic Pneumothorax Rate',
    penalty: 'HAC Reduction Program — accidental lung puncture during procedure',
    icd: 'J95.811 / J93.0 / J93.81 / J93.83',
    risk: 'high',
    hears: [
      '"Chest tube placed" / "pleural drainage"',
      '"Pneumothorax" / "collapsed lung"',
      '"Pleural space entered" / "lung decompressed"',
      '"Thoracentesis" / "pleural effusion drained"',
    ],
    cdi_instinct: [
      'Was this PLANNED (therapeutic drainage) or did something go WRONG?',
      'Did this happen during a procedure with known pleural proximity (central line, thoracentesis)?',
      'Was the pneumothorax pre-existing — present on admission imaging?',
      'Did the physician document the pneumothorax as procedural complication vs. spontaneous?',
    ],
    confirm: [
      'Pneumothorax was NOT present on admission imaging',
      'Pneumothorax occurred during or directly attributable to a procedure',
      'Physician explicitly documents iatrogenic causation',
      'Chest tube or intervention was for the iatrogenic event — not therapeutic for other reasons',
    ],
    never: 'Pneumothorax code in a patient with chest tube placement when admission imaging showed pre-existing pneumothorax — must be confirmed as procedure-caused',
  },
  {
    id: 'PSI-08',
    title: 'In-Hospital Fall with Fracture Rate',
    penalty: 'HAC Reduction Program — new fracture resulting from inpatient fall',
    icd: 'W19.XXXA + S72.xx / S82.xx / S52.xx / S42.xx',
    risk: 'high',
    hears: [
      '"Patient fell" / "found on floor" / "fall from bed"',
      '"Hip fracture" near fall language',
      '"Fracture noted" / "X-ray after fall"',
      '⚠ Fall code + fracture code = AUTOMATIC PSI-08 trigger',
    ],
    cdi_instinct: [
      'Was the fracture the REASON they were admitted — or did it happen DURING the stay?',
      'Was there admission imaging showing no prior fracture?',
      'Did the fall CAUSE the fracture — or did a fracture CAUSE the fall?',
      'Metastatic cancer or severe osteoporosis can cause spontaneous fractures before a fall',
    ],
    confirm: [
      'Post-fall imaging confirms a NEW fracture — not present on admission',
      'Fall event occurred DURING this inpatient admission',
      'Fracture first documented AFTER fall timestamp',
      'Physician documents fall → fracture causation (not fracture → fall)',
    ],
    never: 'Fall code + fracture code together without imaging confirmation of NEW fracture — pathological fractures can pre-exist',
  },
  {
    id: 'PSI-09',
    title: 'Postop Hemorrhage or Hematoma Rate',
    penalty: 'HAC Reduction Program — significant postop bleeding requiring additional treatment',
    icd: 'T81.0XXA / T81.010A / M96.830 / M96.840',
    risk: 'medium',
    hears: [
      '"Hematoma" / "hemorrhage" / "bleeding postop"',
      '"Return to OR for bleeding"',
      '"Evacuation of hematoma" / "transfusion given"',
      '"Drain output increased" / "blood collection"',
    ],
    cdi_instinct: [
      'Is this patient on anticoagulants? Coumadin or Plavix patients bleed more — expected, not always a complication',
      'Was this CLINICALLY SIGNIFICANT or just an incidental CT finding nobody treated?',
      'Was the transfusion for THIS bleeding or for pre-existing anemia?',
      'Did the physician explicitly call this a COMPLICATION requiring treatment?',
    ],
    confirm: [
      'Bleeding required ADDITIONAL INTERVENTION — return to OR, transfusion for hemorrhage, or procedural drainage',
      'Physician explicitly documents as complication requiring treatment',
      'Anticoagulation or coagulopathy is NOT the primary explanation',
      'Bleeding occurred AFTER the procedure — not present pre-surgery',
    ],
    never: 'Hemorrhage/hematoma complication code for incidental findings — minor postop bleeding is expected and does NOT trigger PSI-09',
  },
  {
    id: 'PSI-10',
    title: 'Postop AKI Requiring Dialysis',
    penalty: 'HAC Reduction Program — new dialysis initiation after elective surgery',
    icd: 'N17.0–N17.9 + 5A1D00Z / 5A1D60Z / 5A1D70Z',
    risk: 'high',
    hears: [
      '"Dialysis" / "CRRT" / "hemodialysis"',
      '"Renal failure postop" / "AKI"',
      '"Nephrology consulted" / "creatinine rising"',
      '"Kidney not recovering" / "renal replacement"',
    ],
    cdi_instinct: [
      'Was this patient ALREADY on dialysis before admission? Most common false-positive for PSI-10',
      'Was dialysis ACTUALLY started or just nephrology consulted?',
      'What is their BASELINE creatinine — is this really a change from normal?',
      'Did the physician explicitly document NEW AKI requiring dialysis initiation?',
    ],
    confirm: [
      'Patient was NOT dialysis-dependent or have ESRD prior to this admission',
      'Dialysis was ACTUALLY PERFORMED — not just ordered or consulted',
      'Dialysis indication = NEW AKI — not ongoing ESRD management',
      'AKI developed AFTER the surgical procedure — not present on admission',
    ],
    never: 'AKI requiring dialysis code based on nephrology consult or rising creatinine alone — dialysis must be confirmed as new initiation for new AKI',
  },
  {
    id: 'PSI-11',
    title: 'Postop Respiratory Failure Rate',
    penalty: 'HAC Reduction Program — unexpected respiratory failure after elective surgery',
    icd: 'J95.1 / J95.2 / J96.00 / J96.01 / J96.02',
    risk: 'high',
    hears: [
      '"Still on the vent" / "failed extubation"',
      '"Reintubated" / "couldn\'t wean"',
      '"Back on the vent" / "prolonged ventilation"',
      '"Respiratory failure" / "hypoxic"',
    ],
    cdi_instinct: [
      'What procedure did they have? Cardiac, thoracic, major abdominal — staying on the vent is PLANNED',
      'Did the patient have lung disease before surgery? COPD, fibrosis, obesity hypoventilation = expected difficulty weaning',
      'Did the physician say this was an UNEXPECTED complication — or just vent management?',
      'Slow weaning is NOT respiratory failure — physician must explicitly document it as a complication',
    ],
    confirm: [
      'Postop ventilation was NOT expected or planned for this procedure type',
      'Patient had NO pre-existing pulmonary conditions explaining vent dependency',
      'Physician EXPLICITLY documents respiratory failure as UNEXPECTED complication',
      'Reintubation — if it occurred — was UNPLANNED',
    ],
    never: 'Respiratory failure code based on ventilator language alone — planned postop vent management is NOT a complication',
  },
  {
    id: 'PSI-12',
    title: 'Perioperative PE or DVT Rate',
    penalty: 'HAC Reduction Program — blood clot coded as hospital-acquired on surgical patient',
    icd: 'I26.01 / I26.09 / I26.99 / I82.401 / I82.411 / I82.4xx',
    risk: 'medium',
    hears: [
      '"DVT" / "deep vein thrombosis" / "blood clot"',
      '"Pulmonary embolism" / "PE confirmed"',
      '"Lovenox ordered" / "anticoagulation initiated"',
      '"Positive duplex" / "CTA positive"',
    ],
    cdi_instinct: [
      'Is this an ONCOLOGY patient? Cancer patients clot — this may be disease-related, not procedure-related',
      'Was there imaging BEFORE surgery? Without a pre-admission duplex — how do we know the clot wasn\'t already there?',
      'Is Lovenox for PREVENTION or TREATMENT? Lovenox on every surgical patient ≠ DVT diagnosis',
      'Did the physician actually say DVT as a confirmed diagnosis — or are they treating empirically?',
    ],
    confirm: [
      'Imaging (duplex, CTA, V/Q) confirms a clot EXISTS — not just suspected',
      'Physician documents DVT or PE as a CONFIRMED diagnosis',
      'Anticoagulation is THERAPEUTIC dose — not prophylactic',
      'If oncology or clotting disorder present — physician documents procedure-related causation',
    ],
    never: 'DVT/PE code based on anticoagulation orders alone — Lovenox prophylaxis is NOT a DVT diagnosis and must never trigger a code suggestion',
  },
  {
    id: 'PSI-13',
    title: 'Postop Sepsis Rate',
    penalty: 'HAC Reduction Program — one of the highest-scrutiny and highest-penalty PSI events',
    icd: 'A40.0–A40.9 / A41.01–A41.9 / R65.20 / R65.21',
    risk: 'high',
    hears: [
      '"Sepsis" / "septic" / "septic shock"',
      '"Broad spectrum antibiotics" / "Vancomycin / Pip-tazo"',
      '"Fever postop" / "source control" / "bacteremia"',
      '"SIRS" / "white count elevated"',
    ],
    cdi_instinct: [
      'Did the physician actually SAY SEPSIS? Antibiotics for fever ≠ sepsis — physicians treat empirically constantly',
      'Does this meet Sepsis-3? Need BOTH suspected infection source AND organ dysfunction — elevated WBC alone is not enough',
      'When did fever start? Day 1 postop fever is almost always expected inflammation',
      'Was infection already present BEFORE surgery? Pre-existing UTI or pneumonia = POA, not hospital-acquired',
    ],
    confirm: [
      'Physician EXPLICITLY documents \'sepsis\' as a diagnosis — not just infection, fever, or antibiotics',
      'Documentation supports Sepsis-3: infection source AND organ dysfunction evidence',
      'Infection or sepsis was NOT present on admission',
      'Antibiotics are for TREATMENT — not surgical prophylaxis',
    ],
    never: 'Sepsis code based on antibiotics or postop fever alone — Vancomycin and Pip-tazo do NOT confirm sepsis and must never trigger a sepsis code suggestion',
  },
  {
    id: 'PSI-14',
    title: 'Postop Wound Dehiscence Rate',
    penalty: 'HAC Reduction Program — fascial wound disruption after abdominopelvic surgery',
    icd: 'T81.30XA / T81.31XA / T81.32XA',
    risk: 'medium',
    hears: [
      '"Dehiscence" / "fascial dehiscence" / "evisceration"',
      '"Wound separation" / "wound opened"',
      '"Wound VAC applied" / "wound not healing"',
      '"Return to OR for wound" / "wound breakdown"',
    ],
    cdi_instinct: [
      'What LAYER is involved? Superficial skin separation in obese or diabetic patients is common — does NOT trigger PSI-14',
      'Did this require a RETURN TO OR for repair? Wound VAC alone = wound management, not dehiscence',
      'What is this patient\'s risk profile? Obesity, diabetes, steroids, malnutrition — expected wound healing challenges',
      'Did the SURGEON document what layer was disrupted — not just nursing wound appearance?',
    ],
    confirm: [
      'Surgeon explicitly documents FASCIAL layer or internal operative wound disruption',
      'Required OPERATIVE REPAIR — return to OR for wound closure',
      'Procedure was an ABDOMINOPELVIC OR procedure (PSI-14 denominator requirement)',
      'Wound disruption occurred AFTER surgery — not present pre-operatively',
    ],
    never: 'Wound dehiscence code for superficial skin separation — fascial layer disruption must be explicitly documented by the surgeon',
  },
  {
    id: 'PSI-15',
    title: 'Abdominopelvic Accidental Puncture or Laceration',
    penalty: 'HAC Reduction Program — HIGHEST false-positive risk in the PSI-90 composite',
    icd: 'T81.520A / T81.521A / T81.522A / K91.71',
    risk: 'very-high',
    hears: [
      '"Entered the bowel" / "bladder injury" / "bowel entry"',
      '"Inadvertent cystotomy" / "vessel injury"',
      '"Repaired incidentally" / "unintended entry"',
      '"Enterotomy" / "dissection near [organ]"',
    ],
    cdi_instinct: [
      'Was this truly ACCIDENTAL or just how surgeons describe complex dissection near adhesions?',
      'Did the surgeon use the words: accidental, inadvertent, or unintended? Those SPECIFIC words matter',
      'What is this patient\'s surgical history? Prior abdominal surgeries + radiation = expected proximity to organs',
      'Did this require ADDITIONAL repair beyond what was planned — or was it part of the dissection?',
    ],
    confirm: [
      'Surgeon EXPLICITLY uses: accidental, inadvertent, unintended, or unexpected',
      'Injured structure was NOT expected in operative field given procedure and patient history',
      'Injury required ADDITIONAL repair beyond planned procedure scope',
      'Physician characterizes this as a complication in the operative note',
    ],
    never: 'Accidental puncture code based on anatomical proximity language — ambiguous language = FALSE. Surgeon must explicitly say accidental. Supervisor review required before any release.',
  },
];

// LIVE DEMO SCENARIOS — three real-world false-positive cases
const SCENARIOS = [
  {
    psi: 'PSI-11',
    name: 'The TAVR Respiratory Failure',
    setting: 'Elective admit for TAVR. Critical care attending documenting POD 0 progress note.',
    provider_quote: 'Postprocedure respiratory failure. Extubated to room air postoperatively. No hypoxia, SOB, dyspnea, or tachypnea.',
    ai_detection: 'J95.821 — Acute postprocedural respiratory failure',
    ai_confidence: '0.93',
    conditions: [
      { text: 'Postop ventilation was NOT expected or planned for this procedure type', met: 'pass', evidence: 'TAVR is a minimally invasive transcatheter procedure; routine extubation is expected.' },
      { text: 'Patient had NO pre-existing pulmonary conditions explaining vent dependency', met: 'pass', evidence: 'No pulmonary comorbidities documented.' },
      { text: 'Physician EXPLICITLY documents respiratory failure as UNEXPECTED complication', met: false, evidence: 'Provider used the words "postprocedure respiratory failure" — but the surrounding clinical picture contradicts the diagnosis. Patient extubated to room air with no hypoxia, SOB, dyspnea, or tachypnea documented.' },
      { text: 'Clinical picture supports a true respiratory failure diagnosis', met: false, evidence: 'No clinical criteria for respiratory failure are met. Successful extubation to room air with no respiratory symptoms is incompatible with the diagnosis as written.' },
    ],
    outcome: 'HOLD',
    outcome_reason: 'Provider used the words "post-procedure respiratory failure" — but the same note documents room air extubation with no hypoxia, SOB, dyspnea, or tachypnea. The clinical picture does not support the diagnosis as written.',
    cdi_query: 'The term "post-procedure respiratory failure" is documented, but the same note describes extubation to room air with no respiratory symptoms. Is respiratory failure clinically supported as written?',
    business_impact: 'PSI-11 attribution requires documentation that aligns with clinical evidence. Provider terminology alone — without supporting clinical context — should not drive a postprocedure respiratory failure code.',
  },
  {
    psi: 'PSI-09',
    name: 'The Post-Op Hematoma',
    setting: 'Elective admit for right carotid endarterectomy. POD 1 — return to OR for hematoma evacuation.',
    provider_quote: 'Returned to OR for evacuation of right-sided neck hematoma. Patient continued aspirin and Plavix perioperatively given recent stroke history. Stable post-evacuation.',
    ai_detection: 'T81.0XXA — Hemorrhage and hematoma complicating a procedure',
    ai_confidence: '0.88',
    conditions: [
      { text: 'Bleeding required ADDITIONAL INTERVENTION beyond routine management', met: 'pass', evidence: 'Return to OR for hematoma evacuation confirmed — meets clinical significance threshold.' },
      { text: 'Physician explicitly documents bleeding as a complication requiring treatment', met: 'pass', evidence: 'Hematoma is documented and evacuated as a treated event.' },
      { text: 'Anticoagulation or coagulopathy is NOT the primary explanation', met: false, evidence: 'Patient on dual antiplatelet therapy (aspirin + Plavix) continued perioperatively due to recent stroke. DAPT is a well-documented bleeding risk factor — drug-related vs. surgical causation is unclear.' },
      { text: 'Bleeding occurred AFTER the procedure — not present pre-surgery', met: 'pass', evidence: 'Hematoma developed POD 1 — clearly post-operative.' },
    ],
    outcome: 'HOLD',
    outcome_reason: 'Three of four conditions pass — the AI sees a return-to-OR for postop hematoma and codes it as a surgical complication. But the patient was on dual antiplatelet therapy continued perioperatively for stroke prevention. Drug-induced bleeding has its own coding pathway (D68.32) that, if documented, AVOIDS PSI-09 attribution entirely.',
    cdi_query: 'Please clarify: is the post-operative hematoma characterized as related to continued perioperative dual antiplatelet therapy (aspirin + Plavix for recent stroke), or as a surgical complication independent of anticoagulant effect? Drug-induced bleeding documentation affects PSI-09 attribution.',
    business_impact: 'When perioperative antiplatelet or anticoagulant therapy is continued, drug-induced bleeding documentation (D68.32) can AVOID PSI-09 attribution. Without that clarification, a medication-related bleeding event may be coded as a surgical complication.',
  },
  {
    psi: 'PSI-12',
    name: 'The Oncology Patient DVT',
    setting: 'POD 2 after laparoscopic colon resection for colon cancer. Routine post-op screening duplex.',
    provider_quote: 'Routine post-op screening duplex on POD 2 shows acute DVT in left peroneal vein. Patient has stage III colon adenocarcinoma. Continuing prophylactic Lovenox, will transition to therapeutic dose. Asymptomatic — no pre-op imaging on file.',
    ai_detection: 'I82.401 — Acute DVT of left lower extremity, unspecified vessel',
    ai_confidence: '0.91',
    conditions: [
      { text: 'Imaging confirms a clot EXISTS — not just suspected', met: 'pass', evidence: 'Duplex confirms acute DVT in left peroneal vein.' },
      { text: 'Physician documents DVT as a CONFIRMED diagnosis', met: 'pass', evidence: 'DVT explicitly documented; anticoagulation being transitioned to therapeutic dose.' },
      { text: 'Anticoagulation is THERAPEUTIC — not prophylactic', met: 'pass', evidence: 'Plan documents transition from prophylactic to therapeutic dose.' },
      { text: 'For oncology patients: causation AND POA status both addressed', met: false, evidence: 'Stage III colon adenocarcinoma is a known thrombosis risk factor (cancer-associated thrombosis is medically distinct from procedural thrombosis). Additionally, no pre-operative imaging on file — POA status cannot be confirmed without baseline imaging or clinical assessment.' },
    ],
    outcome: 'HOLD',
    outcome_reason: 'Three conditions pass — the AI sees confirmed imaging, confirmed diagnosis, and therapeutic anticoagulation. But without explicit documentation of causation (cancer-related vs. procedure-related) and POA status, the AI cannot distinguish a procedural complication from disease-related thrombosis.',
    cdi_query: 'Please clarify in the documentation: (1) Is the DVT characterized as cancer-associated (related to known malignancy) or as procedure-related? (2) Given no pre-operative imaging is available, can POA status be clinically assessed and documented? Both causation and POA affect PSI-12 attribution.',
    business_impact: 'PSI-12 attribution depends on both causation and POA status. When pre-operative imaging is unavailable and the patient has a known thrombosis risk factor like active malignancy, both questions must be addressed before the code can be released.',
  },
];
